name: databub-build

# Only trigger on:
# - master branch
# - PR or Pull Request event types
# - Source/test files
on:
  push:
    branches:
      - master
    paths:
      - 'tests'
      - 'datahub_core/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '*.py'
      - '*.ini'
      - '*.yml'
      - '.github/workflows/build.yml'
  pull_request:
    paths:
      - 'tests'
      - 'datahub_core/**'
      - 'mkdocs.yml'
      - 'requirements.txt'
      - '*.py'
      - '*.ini'
      - '*.yml'
      - '.github/workflows/build.yml'

jobs:
  datahub-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Install dependencies
        run: python -m pip install -r requirements.txt
      - name: run pylint
        run: python -m pylint ./datahub_core --disable=R,C,W
      - name: Check test coverage
        run: python -m pip install pytest pytest-cov coverage
      - name: Run unit tests
        run: python -m pytest --cov-report xml --cov=. --junitxml=test_results.xml ./tests
